`Neural Network Regression w/TensorFlow`

### Coverage:
* Input/Output shapes of a reg model (features and labels)
* Architecture of a reg model
* Creating custom data to view and fit
* Steps in modelling `create a model, compile, fit, evaluate *CrCoFiEv*`
* Evaluation Methods
* Saving & Loading Models

In [1]:
# lets see how you do comments
import tensorflow as tf
import numpy as np
tf.__version__
import matplotlib.pyplot as plt

2022-12-29 17:15:45.630292: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


`Regression Inputs and Outputs`
* For a Reg problem, the shape of the [output] is normally 1; shape=[1] as we often try to predict some number.

In [2]:
# Create Features / inputs
X = np.array([-7, -4, -1, 2, 5, 8, 11, 14]) # uppercase 
# create labels
y = np.array([3,6,9,12,15,18,21,24]) #lower case
# visualize
# plt.scatter(X, y)

In [3]:
# what is the pattern btn the features and the labels
y == X + 10 # this is the relationship our neural net was supposed to learn

array([ True,  True,  True,  True,  True,  True,  True,  True])

`What then might the shapes be for our Input/Output`

In [4]:
X.shape, y.shape

((8,), (8,))

In [5]:
X, y

(array([-7, -4, -1,  2,  5,  8, 11, 14]),
 array([ 3,  6,  9, 12, 15, 18, 21, 24]))

In [6]:
# create a demo tensor for or housing price prediction problem
house = tf.constant(np.array([[10,11,12,13], [1,2,3,4], [6,7,8,9]]), dtype=tf.float32)
price = tf.constant([1243537])
house, price

2022-12-29 17:15:49.553527: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[10., 11., 12., 13.],
        [ 1.,  2.,  3.,  4.],
        [ 6.,  7.,  8.,  9.]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1243537], dtype=int32)>)

In [7]:
# create demo with a string input
house_info = tf.constant(["bedroom", "bathroom", "garage"])
house_price = tf.constant([12489141])
house_info, house_price

(<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'bedroom', b'bathroom', b'garage'], dtype=object)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([12489141], dtype=int32)>)

* wanna create a prediction feature : X[0] what is the equivalent y[?]

In [8]:
# turn the np arrays into tensors
X = tf.constant(X)
y = tf.constant(y)
X,y

(<tf.Tensor: shape=(8,), dtype=int64, numpy=array([-7, -4, -1,  2,  5,  8, 11, 14])>,
 <tf.Tensor: shape=(8,), dtype=int64, numpy=array([ 3,  6,  9, 12, 15, 18, 21, 24])>)

In [9]:
X[0].shape, y[0].shape # these are scalar values, have no dimension

(TensorShape([]), TensorShape([]))

### Prediction Feature : Building a model
* Creating a Model : `define input hidden and output layer`
* Compile the model : `define loss function and the optimizer and evaluation metric`
* Fit the Model : `let the model try to find patterns btn X(features) and y(labels)`

In [10]:
 # set random seed for reproducibility
tf.random.set_seed(42)

# # create a model using the Sequential API - this is a method of going through all things sequentially
# model = tf.keras.models.Sequential([
#     tf.keras.layers.Dense(1)
# ]) # create a list within Sequential Method instead of using .add

model = tf.keras.models.Sequential() # to create a model using Sequential API, shape must be defined
model.add(tf.keras.layers.Input(shape=(1,)))

model.add(tf.keras.layers.Dense(50, activation=None))
model.add(tf.keras.layers.Dense(50, activation=None))
# model.add(tf.keras.layers.Dense(100, activation='relu'))

model.add(tf.keras.layers.Dense(1))

# compile the model
model.compile(loss=tf.keras.losses.mae, # mean abs error
            optimizer=tf.keras.optimizers.Adam(lr=0.01), #stochastic gradient descend
            metrics=["mae"]
)

`metrics: human readable and interpretation over the models performance`

In [14]:
# fit the model - let us find patterns
model.fit(X, y, epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 9ms/step - loss: 0.2896 - mae: 0.2896
Epoch 2/200
1/1 [==============================] - 0s 10ms/step - loss: 0.0666 - mae: 0.0666
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 0.2196 - mae: 0.2196
Epoch 4/200
1/1 [==============================] - 0s 11ms/step - loss: 0.1958 - mae: 0.1958
Epoch 5/200
1/1 [==============================] - 0s 11ms/step - loss: 0.0412 - mae: 0.0412
Epoch 6/200
1/1 [==============================] - 0s 11ms/step - loss: 0.0693 - mae: 0.0693
Epoch 7/200
1/1 [==============================] - 0s 9ms/step - loss: 0.1147 - mae: 0.1147
Epoch 8/200
1/1 [==============================] - 0s 11ms/step - loss: 0.0739 - mae: 0.0739
Epoch 9/200
1/1 [==============================] - 0s 11ms/step - loss: 0.1753 - mae: 0.1753
Epoch 10/200
1/1 [==============================] - 0s 12ms/step - loss: 0.1729 - mae: 0.1729
Epoch 11/200
1/1 [==============================] - 0s 12ms/step - loss:

In [15]:
# make a predction for what x[17] should be
model.predict([17])

1/1 [==============================] - 0s 110ms/step


array([[27.366678]], dtype=float32)

#### Alter the Model for Improvememt