# WorkFlow

* Intro to Tensors
* Getting info from Tensors
* Manipulating Tensors
* Tensors and Numpy
* Using @tf.function (speed up regular python fucntion)
* Using GPU/TPU w/TensorFlow
* Excercise


### Intro to `Tensors`

In [1]:
# import tensorflow

import tensorflow as tf
print(tf.__version__)

2022-12-29 13:21:08.659412: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.11.0


In [2]:
# creating tensors with tf.contant()
scalar = tf.constant(7)
scalar
# has an empty shape
# tf.constant? ceates a constant tensor from a tensor-like object

2022-12-29 13:21:11.761935: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check for number of dimensions
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10]) # pass a python list to constant function
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimension of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([
    [10,7],
    [7,10]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# check for dimension
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[1.,4.],
[3.,5.],
[9., 12.]], dtype=tf.float16) # reduce data size occuiance on disk

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1.,  4.],
       [ 3.,  5.],
       [ 9., 12.]], dtype=float16)>

In [9]:
another_matrix.ndim #number of elements in a shape

2

In [10]:
# create another tensor
tensor = tf.constant(
    [[[1,2,3,],
        [4,5,6]],
        [[7,8,9],
        [10,11,12]],
        [[13,14,15],
        [16,17,18]]]
)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

### Creating Tensors with `tf.Variable`

In [12]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# lets chnag one of the elements in a chnagable tensor
# changable_tensor[0] = 13

In [14]:
# trying assign
changable_tensor[1].assign(15)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 15], dtype=int32)>

### Creating Random Tensors

- The neural net always initializes itself with random weights/random tensors
- Adjusts the random weights wrt what the net learns

In [15]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(4,2))
random_1

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [16]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(4,2))
random_2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [17]:
# with both having a reproducibility value of 42
random_1, random_1, random_1 == random_2 # check hoe they compare

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
random_2 = tf.random.Generator.from_seed(2) # change the seed value to 2 and see how that compares
random_2 = random_2.normal(shape=(4,2))
random_2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.1012345 , -0.2744976 ],
       [ 1.4204658 ,  1.2609464 ],
       [-0.43640924, -1.9633987 ],
       [-0.06452483, -1.056841  ]], dtype=float32)>

In [19]:
random_2, random_1, random_2 == random_1 # change the seed value and the reproducibility is different

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-0.1012345 , -0.2744976 ],
        [ 1.4204658 ,  1.2609464 ],
        [-0.43640924, -1.9633987 ],
        [-0.06452483, -1.056841  ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False],
        [False, False]])>)

### Shuffling: 
* Inheret Order shouldn't affect learning

In [20]:
# not_shuffled = tf.random.Generator.from_seed(42)
# not_shuffled = not_shuffled.normal(shape=(3,2))
# not_shuffled

not_shuffled = tf.constant([[1,2],
[3,4],
[5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [21]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [22]:
not_shuffled, shuffled, not_shuffled == shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [5, 6],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [False, False],
        [False, False]])>)

In [23]:
# global set_seed
tf.random.set_seed(42) # global
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [24]:
# create a tensor array of all zeros
tf.zeros(shape=(2,4), dtype=tf.int32)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [25]:
tf.ones([4,6], tf.float64)

<tf.Tensor: shape=(4, 6), dtype=float64, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])>

#### Convert a NumPy Array into a Tensor

In [26]:
# import numpy
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [27]:
# convert the Array into a Tensor
tensor_t = tf.constant(numpy_A)
tensor_t
tensor_tshaped = tf.constant(numpy_A, shape=(2,4,3))
tensor_tshaped

<tf.Tensor: shape=(2, 4, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int16)>

In [28]:
numpy_B = np.arange(12.3,31.1, dtype=np.float16)
numpy_B

array([12.3, 13.3, 14.3, 15.3, 16.3, 17.3, 18.3, 19.3, 20.3, 21.3, 22.3,
       23.3, 24.3, 25.3, 26.3, 27.3, 28.3, 29.3, 30.3], dtype=float16)

In [29]:
tensor_tb = tf.constant(numpy_B, dtype=tf.int16)
tensor_tb

<tf.Tensor: shape=(19,), dtype=int16, numpy=
array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30], dtype=int16)>

## Getting information from a tensor.
* Shape 
* Rank
* Axis/Dimension
* Size

In [30]:
# create a rank_4 tensor: rank - no. of tensor dimensions
rank_4_tensor = tf.zeros([2,3,4,5], dtype=tf.int32)
# see how it looks like
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [31]:
# create a rank_2 tensor: no. of dimension
rank_2_tensor = tf.zeros([3,2], dtype=tf.int16)
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)>

In [32]:
# get the 1st element of the tensor
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)>

In [33]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [34]:
rank_4_tensor.ndim

4

In [35]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [36]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])

In [37]:
t.shape, t.ndim, tf.size(t)

(TensorShape([2, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [38]:
t

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [39]:
# deep look into the attributes of our tensor
print("Datatype of Every Element: ", rank_4_tensor.dtype)
print("Number of Dimension (rank): ", rank_4_tensor.ndim)
print("Shape of Tensor: ",rank_4_tensor.shape)

Datatype of Every Element:  <dtype: 'int32'>
Number of Dimension (rank):  4
Shape of Tensor:  (2, 3, 4, 5)


In [40]:
print("Elements along the 0 axis: ",rank_4_tensor.shape[0])

Elements along the 0 axis:  2


In [41]:
print("Elements along the last axis: ", rank_4_tensor.shape[-1])

Elements along the last axis:  5


In [42]:
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor).numpy())

Total number of elements in our tensor:  120


#### Indexing Tensors

In [43]:
#python list and indexing
values_to_index = [1,2,3,4,5]
# get the first three elements in the list
values_to_index[:3]

[1, 2, 3]

In [44]:
# get the first two elements of each dimension
rank_4_tensor[:2,:3,:1,:]

<tf.Tensor: shape=(2, 3, 1, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0]]]], dtype=int32)>

> Adding an Extra Dimension into a Tensor

In [45]:
# create a rank 2 tensor
rank_2_tensor = tf.constant([[5,7],
[9,2]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [46]:
# get the last item [-1] of each of the dimensions
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2], dtype=int32)>

In [47]:
# create a rank_3 out of rank_2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [7]],

       [[9],
        [2]]], dtype=int32)>

In [48]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [9, 2]], dtype=int32)>

In [49]:
#expand using another method
tf.expand_dims(rank_2_tensor, axis=-1) #expnads the last axis of the rank_2_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [7]],

       [[9],
        [2]]], dtype=int32)>

In [50]:
# expand from the front
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 7],
        [9, 2]]], dtype=int32)>

In [51]:
# expand from the middlw
tf.expand_dims(rank_2_tensor, axis=1)#.shape.as_list()

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[5, 7]],

       [[9, 2]]], dtype=int32)>

#### Operations on Tensors, Manipulating Tensors

**Basic Operations : ADMS** : `Element-wise ops`

In [52]:
tensor = tf.constant([[6.3,7.8],
[2,3]], dtype=tf.float16)
tensor_A = tensor * 10
tensor_A 

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[63., 78.],
       [20., 30.]], dtype=float16)>

Its a Computing advantage when we use tf's built in functions for numeric ops

In [53]:
tf_built = tf.subtract(tensor_A, 12.4) # dtypes must be the same
tf_built

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[50.6, 65.6],
       [ 7.6, 17.6]], dtype=float16)>

#### **Matrix Multiplication**

In [54]:
# use the matmul
tensor

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[6.3, 7.8],
       [2. , 3. ]], dtype=float16)>

In [55]:
check_shape = tf.matmul(tensor, tensor_A)
check_shape.shape

TensorShape([2, 2])

In [56]:
check_shape

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[553. , 725.5],
       [186. , 246. ]], dtype=float16)>

In [57]:
# matrix multiplication with Python
check_shape_1 = tensor_A @ tensor
check_shape_1, check_shape, check_shape_1 == check_shape

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[553. , 725.5],
        [186. , 246. ]], dtype=float16)>,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[553. , 725.5],
        [186. , 246. ]], dtype=float16)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

In [58]:
# create a [3,2] matrix

X = tf.constant([[1,2],[3,4],[5,6]]).numpy()

Y = tf.constant([[7,8],[9,10],[11,12]]).numpy()

X, Y

(array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32))

In [59]:
# matrix multiply X and Y
# X @ Y
# tf.matmul(X,Y)

# Both multiplications fuction throw in an error : Matrix size-incompatible:


In [60]:
# Y = tf.transpose(Y)
# tf.matmul(X,Y)

In [61]:
Y

array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)

In [62]:
# X = tf.transpose(X)
# tf.matmul(X,Y)

In [63]:
X,Y

(array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32))

In [64]:
# perfome matrix multiplication btn X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [65]:
# perfom matrix multiplication btn X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [66]:
# check the difference btn reshaped and transposed and normal Y

# normal Y
print("Normal Y: ")
print(Y, "\n")

print("Reshaped Y: ")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Transposed Y: ")
print(tf.transpose(Y), "\n")



Normal Y: 
[[ 7  8]
 [ 9 10]
 [11 12]] 

Reshaped Y: 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



* Reduced Precision float32 to float16

In [67]:
# create a 32--bit float
B = tf.constant([17,74])
B, B.dtype


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([17, 74], dtype=int32)>,
 tf.int32)

In [68]:
# reduce to 16-bit instead of 32-bit
D = tf.cast(B, dtype=tf.float16) # casts a tensor into a new type
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([17., 74.], dtype=float16)>,
 tf.float16)

### Aggregating Tensors

* Condense them from multiple values to smaller amounts:
* From a whole group, cluster to reduce occupied size

In [69]:
# get the absolute values.
M = tf.constant([-12, -129])
tf.abs(M)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 12, 129], dtype=int32)>

In [70]:
N = tf.Variable([12,-13,-109])
tf.cast(N, dtype=tf.int16)
# get the abs value
tf.abs(N)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 12,  13, 109], dtype=int32)>

In [71]:
# create a random tensor with values btn 0 and 100

E = tf.constant(np.random.randint(0, 100, 50)).numpy()
E, E.shape, E.ndim, tf.size(E).numpy()

(array([86, 81, 45, 79,  8, 47, 82, 79, 16, 45, 91, 52, 72, 85,  4, 80, 85,
        34,  7, 61, 82, 49, 87, 43, 98, 87, 93, 61, 52, 37, 47, 81, 75, 22,
        90, 16, 69, 58, 92, 51, 11, 49, 93, 26, 18, 68,  2, 20, 64, 24]),
 (50,),
 1,
 50)

In [72]:
# sum 
print(tf.reduce_min(E), "\n")
print(tf.reduce_max(E), "\n")

print(tf.reduce_mean(E), "\n")
print(tf.reduce_sum(E))

tf.Tensor(2, shape=(), dtype=int64) 

tf.Tensor(98, shape=(), dtype=int64) 

tf.Tensor(56, shape=(), dtype=int64) 

tf.Tensor(2804, shape=(), dtype=int64)


`Find variance and standard dev using tf.method()`

In [73]:
E_v = tf.cast(E, dtype=tf.float32)
variance = tf.math.reduce_variance(E_v)
variance.numpy()

818.1936

In [74]:
# standard deviation - measure of dispersion of a dataset
# square-root of variance
std_dev = tf.math.reduce_std(E_v)
std_dev.numpy()

28.604084

In [75]:
tf.math.sqrt(variance).numpy() == std_dev.numpy()

True

`Positional Minimum and Maximum`

In [76]:
# create a tensor with 50 elements.
# at which index does the maximum value occur
tf.argmax()
np.argmax()

TypeError: Missing required positional argument

In [77]:
# create a tensor with 60 elements
tf.random.set_seed(42) # global seed
fifty = tf.random.uniform(shape=[60])
fifty.numpy()

array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043,
       0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
       0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ],
      dtype=float32)

In [78]:
tf.size(fifty).numpy(), fifty.shape, fifty.ndim

(60, TensorShape([60]), 1)

In [79]:
# let us now find the positional maximum
tf.argmax(fifty).numpy()

52

In [80]:
# get the value of the 52nd index
fifty[tf.argmax(fifty)].numpy()

0.97803545

In [81]:
# find the positional minimum
tf.argmin(fifty).numpy()

16

In [82]:
# get the specific value of the 16th position
fifty[tf.argmin(fifty)].numpy()

0.009463668

`Squeezing a Tensor [Shape]`

In [83]:
# create a random tensor, use shape param to add single dimns to the start

# initialte a global seed
tf.random.set_seed(42)
# create a random tensor and specify the shape
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50]).numpy()
G

array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)

In [84]:
# shape is the most important parameter
G.shape

(1, 1, 1, 1, 50)

In [85]:
# squeeze - removes all dimension of size 1 from a tensor
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

*TensorShape([50]) - This is the end result*

`One-Hot Encoding`

In [86]:
# create a list of four elements / indices
some_list = [0,1,2,3,4] # could be a rep of fruits, banana, ornage, mangoes, pineaples, apples

# one hot encode our list

tf.one_hot(some_list, depth=5, dtype=tf.int32).numpy() #set the depth based on the number of elements in our index

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

`Revisit later on.....`

In [87]:
# # create my list of fruits and one-hot encode them
# fruit_list = ['banana', 'apple', 'orange', 'cassava', 'mangoes']
# fruit_list
# # one hot encode these values as in
# tf.one_hot(fruit_list, depth=5)

## Tensors and Numpy


In [88]:
# create a tensor directly from a numpy array
J = tf.constant(np.array([10,100,18,193]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 10, 100,  18, 193])>

In [89]:
# create a numpy array
J = np.array([10,11,12,12,32,43])
type(J) # confirm the type

numpy.ndarray

In [90]:
# convert the np.array into a tensor
J = tf.constant(J)
# check the type of J
type(J) # it s a tensor

tensorflow.python.framework.ops.EagerTensor

In [91]:
# how about we convert it to an array
J = np.array(J)
type(J)

numpy.ndarray

In [92]:
numpy_J = tf.constant(np.array([12.,11,123,413])) # create a numpy array & convert to a tensor
tens_floe = tf.constant([12,12,23.1,3432]) # create a tensor directly using tensor

# check for difference in datatype - dtype
numpy_J.dtype, tens_floe.dtype

(tf.float64, tf.float32)